artifacts_root: artifacts 

data_ingestion:
# data ingestion settings
  root_dir: artifacts/data_ingestion
  data_source_url: "https://example.com/data"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion